name: release.yml
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x.x'
      - name: Restore Dependencies
        run: dotnet restore
      - name: Fetch Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
      - name: Get Version
        id: get_version
        run: |
          $out = ([xml](Get-Content './Loci/Loci.csproj')).Project.PropertyGroup.Version
          Write-Output "ver=$out" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          $ver = ${{ steps.get_version.outputs.ver }}
          Invoke-Expression 'dotnet build --no-restore --configuration Release --nologo -p:Version=$ver -p:FileVersion=$ver -p:AssemblyVersion=$ver'
      - name: Archive
        run: Compress-Archive -path "Loci/bin/Release/*" -DestinationPath "Loci.zip"
      - name: Check for Release
        id: check_release_needed
        run: |
          $test = git tag -l | Select-String -Pattern "${{ steps.get_version.outputs.ver }}
          if ($test -ne $null) {
          Write-Output "newtag=false" >> "$GITHUB_OUTPUT"
          } else {
          git config --global user.name "Actions User"
          git config --global user.email "actions@github.com"
          git tag ${{ steps.get_version.outputs.ver }}
          git push --tags
          Write-Output "newtag=true" >> "$GITHUB_OUTPUT"
          }
      - name: Upload Build Artifact
        if: ${{ steps.check_release_needed.outputs.newtag }}
        uses: actions/upload-artifact@v4.6.2
        with:
          path: |
            ./Loci/bin/Release/*
      - name: Create Release
        if: ${{ steps.check_release_needed.outputs.newtag }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.ver }}
          release_name: Loci ${{ steps.get_version.outputs.ver }}
          draft: 'false'
          prerelease: 'false'
      - name: Upload Release Asset
        if: ${{ steps.check_release_needed.outputs.newtag }}
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Loci.zip
          asset_name: Loci.zip
          asset_content_type: application/zip
      - name: Update repo.json
        if: ${{ steps.check_release_needed.outputs.newtag }}
        run: |
          $ver = '${{ steps.get_version.outputs.ver }}'
          $path = './repo.json'
          $json = Get-Content -Raw $path | ConvertFrom-Json
          $json[0].AssemblyVersion = $ver
          $json[0].DownloadLinkInstall = ${{ steps.upload_release_asset.outputs.browser_download_url }}
          $json[0].DownloadLinkUpdate = ${{ steps.upload_release_asset.outputs.browser_download_url }}
          $json[0].DownloadLinkTesting = ${{ steps.upload_release_asset.outputs.browser_download_url }}
          $content = $json | ConvertTo-Json -AsArray
          set-content -Path $path -Value $content
      - name: Commit repo.json
        if: ${{ steps.check_release_needed.outputs.newtag }}
        run: |
          git config --global user.name "Actions User"
          git config --global user.email "actions@github.com"
          git fetch origin main
          git branch -f main ${{ github.sha }}
          git checkout main
          git add repo.json
          git commit -m "[CI] Updating repo.json for ${{ steps.get_version.outputs.ver }}\n\nskip-checks:true" || true
          git push origin main
